### ISSUE TITLE
Нужно жоще c .jshintrc

### ISSUE THREAD

**Issue by azproduction** [enb-make/npm-package#1]
++

``` js
{
    "maxerr": 5,
    "maxdepth": 2,
    "maxstatements": 12,
    "maxcomplexity": 5
}
```

**Comment by mdevils** [comment]
Согласен. Pull-request?)

**Comment by noway** [comment]
Не слишком ли мало 5? Мак-Кейб советовал ограничивать себя [десятью](https://ru.wikipedia.org/wiki/%D0%A6%D0%B8%D0%BA%D0%BB%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D1%81%D0%BB%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C#.D0.9E.D0.B3.D1.80.D0.B0.D0.BD.D0.B8.D1.87.D0.B5.D0.BD.D0.B8.D0.B5_.D1.81.D0.BB.D0.BE.D0.B6.D0.BD.D0.BE.D1.81.D1.82.D0.B8_.D0.BF.D1.80.D0.B8_.D1.80.D0.B0.D0.B7.D1.80.D0.B0.D0.B1.D0.BE.D1.82.D0.BA.D0.B5). 
Может быть некоторые и могут ограничивать себя до такой степени, но 10 вполне достаточно для понимания кода.
Предлагаю сделать более либеральные 10 пунктов.

UPD: ещё бы `maxdepth` сделать 5, ИМХО.

**Comment by azproduction** [comment]
@noway421 я за 5 CC еще ни разу не выходил. Напиши для себя функцию с CC 10 и 5 и ты поймешь, что 5 - это павильный выбор ;-)

`maxdepth=5` ты предлагаешь разрешить такое?

``` js
for (var i = 0; i < 150505; i++) {
    for (var j = 0; j < 150505; j++) {
        if (j === 1589) {
            for (var k = 0; k < 150505; k++) {
                if (k === 1589) {
                    doStuff();
                }
            }
        }
    }
}
```

**Comment by noway** [comment]
Смотря что нужно писать. Если обычную декларатившину, то в 5 легко уложиться. 
А если выйти немного дальше и написать алгоритм? 
С массивом покалядовать, объект перестроить. 

Не надо занижать потребности разраба.
Конечно любители могут для этого сделать целый класс, но слишком жирно.

> maxdepth

С учетом того, что для `for (key in value)` нужна дополнительная проверка `hasOwnProperty`, то да.
Вы можете уменьшить вложенность с помощью continue, но линтеры не понимают такую запись.  

Хотя и 4 хватит, таки.

Можно, конечно, делать исключения для некоторых файлов, но это не однородно, имхо.
