### ISSUE TITLE
Grunt

### ISSUE THREAD

**Issue by noway** [enb-make/npm-package#6]
Может быть лучше использовать grunt вместо велосипедных Makefile'ов? 
Плюсы: удобное подключение новых модулей, работает не только в юниксах, распространенность.
Минусы: тяжелый.

**Comment by azproduction** [comment]
Makefile используется исключительно для "красивого package.json" https://github.com/enb-make/npm-package/issues/2 Я за Grunt для повседневных задач, но тут немного другая история.

**Comment by megatolya** [comment]
Было бы круто при инициализации выбрать make или grunt
